apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bartestargo
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - git:
        repoURL: https://github.com/BarAshkenazi/my-deployments.git
        revision: HEAD
        pathParamPrefix: serviceRepo
        directories:
          - path: dep/deployments/*/environments/*/*
        values:
          depName: '{{index .serviceRepo.path.segments 2}}'
          env: '{{index .serviceRepo.path.segments 4}}'
          region: '{{index .serviceRepo.path.segments 5}}'
  template:
    metadata:
      name: '{{.values.depName}}-{{.values.env}}-{{.values.region}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/BarAshkenazi/my-deployments.git
        targetRevision: HEAD
        path: 'dep/deployments/{{.values.depName}}/environments/{{.values.env}}/{{.values.region}}'
      destination:
        server: 'https://kubernetes.default.svc'     
        namespace: '{{.values.depName}}'
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            my.com/environment: '{{.values.env}}'
            my.com/region: '{{.values.region}}'
        syncOptions:
          - CreateNamespace=true 
